import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
//import static javaapplication2.Mycv.sd2;
/**
 *
 * @author manisha
 */
public class Admin2 extends javax.swing.JFrame {

    /**
     * Creates new form User2
     */
    static String sd1;
    Statement stmt;
    String s;
    public Admin2(String sid) {
        sd1=sid;
        //super("ADMINISTRATOR");
        initComponents();
        try{
            Class.forName("org.gjt.mm.mysql.Driver");

            31

            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/campus system","root","");
            stmt=(Statement) con.createStatement();
        }catch(Exception ee){}

        try {
            ResultSet rs=stmt.executeQuery("Select name from apass where
                    username='"+sd1+"'");
                    rs.next();
            s=rs.getString(1);

        }catch(Exception ee){}
        ss.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        32

        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        ss = new javax.swing.JLabel();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin2(sd1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel ss;
    // End of variables declaration
}