/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
//import static javaapplication2.Mycv.sd2; 
import javax.swing.JOptionPane;


public class Adcv extends javax.swing.JFrame {


    Statement stmt;
    String sd2;

    public Adcv() {
        super("COMPANY STATUS");
        initComponents();
        try{
            Class.forName("org.gjt.mm.mysql.Driver");

            28

            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/campus system","root","");
            stmt=(Statement) con.createStatement();
        }catch(Exception ee){}

    }
    /**
     * This method is called from within the constructor to initialize the form. 
     * WARNING: Do NOT modify this code. The content of this method is always 
     * regenerated by the Form Editor. 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                           
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        private javax.swing.JLabel jLabel9;
        // End of variables declaration
    }