/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Creates new form End
 /**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */

        } catch (IllegalAccessException ex) {

        java.util.logging.Logger.getLogger(End.class.getName()).log(java.util.logging.Level.SEV
                                                                            ERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        java.util.logging.Logger.getLogger(End.class.getName()).log(java.util.logging.Level.SEV
                                                                            ERE, null, ex);
        }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        new End(sd2).setVisible(true);
    }
});

        46

        }

// Variables declaration - do not modify
private javax.swing.JButton jButton1;
private javax.swing.JLabel jLabel1;
// End of variables declaration
}
